"""initial schema

Revision ID: c228c2a77f59
Revises: 
Create Date: 2026-02-12 15:39:06.168208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c228c2a77f59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_anomaly',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('current_cost', sa.Float(), nullable=True),
    sa.Column('expected_cost', sa.Float(), nullable=True),
    sa.Column('deviation_percent', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_anomaly_provider'), 'cost_anomaly', ['provider'], unique=False)
    op.create_index(op.f('ix_cost_anomaly_service'), 'cost_anomaly', ['service'], unique=False)
    op.create_index(op.f('ix_cost_anomaly_severity'), 'cost_anomaly', ['severity'], unique=False)
    op.create_index(op.f('ix_cost_anomaly_timestamp'), 'cost_anomaly', ['timestamp'], unique=False)
    op.create_table('llm_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_id'), 'llm_usage', ['id'], unique=False)
    op.create_index(op.f('ix_llm_usage_model'), 'llm_usage', ['model'], unique=False)
    op.create_index(op.f('ix_llm_usage_provider'), 'llm_usage', ['provider'], unique=False)
    op.create_index(op.f('ix_llm_usage_timestamp'), 'llm_usage', ['timestamp'], unique=False)
    op.create_table('optimization_action',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('estimated_savings', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('auto_approved', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_action_action_type'), 'optimization_action', ['action_type'], unique=False)
    op.create_index(op.f('ix_optimization_action_risk_level'), 'optimization_action', ['risk_level'], unique=False)
    op.create_index(op.f('ix_optimization_action_status'), 'optimization_action', ['status'], unique=False)
    op.create_index(op.f('ix_optimization_action_timestamp'), 'optimization_action', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimization_action_timestamp'), table_name='optimization_action')
    op.drop_index(op.f('ix_optimization_action_status'), table_name='optimization_action')
    op.drop_index(op.f('ix_optimization_action_risk_level'), table_name='optimization_action')
    op.drop_index(op.f('ix_optimization_action_action_type'), table_name='optimization_action')
    op.drop_table('optimization_action')
    op.drop_index(op.f('ix_llm_usage_timestamp'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_provider'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_model'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_id'), table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_index(op.f('ix_cost_anomaly_timestamp'), table_name='cost_anomaly')
    op.drop_index(op.f('ix_cost_anomaly_severity'), table_name='cost_anomaly')
    op.drop_index(op.f('ix_cost_anomaly_service'), table_name='cost_anomaly')
    op.drop_index(op.f('ix_cost_anomaly_provider'), table_name='cost_anomaly')
    op.drop_table('cost_anomaly')
    # ### end Alembic commands ###
